import { zodResolver } from "@hookform/resolvers/zod";
import { useState, type ReactNode } from "react";
import { useForm } from "react-hook-form";
import { Link, useNavigate } from "react-router-dom";
import { loginSchema, registerSchema, type LoginInput, type RegisterInput } from "@carebridge/shared";
import { useAuth } from "../contexts/AuthContext";
import { api } from "../services/api";

export function AuthPage({ mode }: { mode: "login" | "register" }) {
  const registerMode = mode === "register"; const navigate = useNavigate(); const { signIn } = useAuth(); const [error, setError] = useState("");
  const form = useForm<any>({ resolver: zodResolver(registerMode ? registerSchema : loginSchema) });
  async function submit(values: RegisterInput | LoginInput) { try { setError(""); const { data } = await api.post(`/auth/${registerMode ? "register" : "login"}`, values); signIn(data.token, data.user); navigate("/patient"); } catch (err: any) { setError(err.response?.data?.error?.message ?? "Unable to continue. Please try again."); } }
  return <main className="min-h-screen bg-slate-950 px-6 py-16 text-slate-100"><section className="mx-auto max-w-md rounded-2xl bg-white p-8 text-slate-900 shadow-xl"><p className="text-sm font-semibold text-teal-700">CareBridge AI</p><h1 className="mt-2 text-3xl font-bold">{registerMode ? "Create your account" : "Welcome back"}</h1><form className="mt-7 space-y-4" onSubmit={form.handleSubmit(submit)}>{registerMode && <><Field label="Full name" error={form.formState.errors.fullName?.message}><input {...form.register("fullName" as never)} /></Field><Field label="Role" error={form.formState.errors.role?.message}><select {...form.register("role" as never)} defaultValue="PATIENT"><option value="PATIENT">Patient</option><option value="DONOR">Donor</option><option value="HOSPITAL">Hospital</option><option value="NGO">NGO</option></select></Field></>}<Field label="Email" error={form.formState.errors.email?.message}><input type="email" {...form.register("email" as never)} /></Field><Field label="Password" error={form.formState.errors.password?.message}><input type="password" {...form.register("password" as never)} /></Field>{error && <p className="text-sm text-rose-700">{error}</p>}<button className="w-full rounded-lg bg-teal-700 px-4 py-3 font-semibold text-white disabled:opacity-60" disabled={form.formState.isSubmitting}>{form.formState.isSubmitting ? "Please wait…" : registerMode ? "Create account" : "Sign in"}</button></form><p className="mt-5 text-sm text-slate-600">{registerMode ? "Already registered?" : "New to CareBridge?"} <Link className="font-semibold text-teal-700" to={registerMode ? "/login" : "/register"}>{registerMode ? "Sign in" : "Create an account"}</Link></p></section></main>;
}
function Field({ label, error, children }: { label: string; error?: string; children: ReactNode }) { return <label className="block text-sm font-medium">{label}<span className="mt-1 block [&_input]:w-full [&_input]:rounded-lg [&_input]:border [&_input]:border-slate-300 [&_input]:p-3 [&_select]:w-full [&_select]:rounded-lg [&_select]:border [&_select]:border-slate-300 [&_select]:p-3">{children}</span>{error && <span className="mt-1 block text-xs text-rose-700">{error}</span>}</label>; }
