import { zodResolver } from "@hookform/resolvers/zod";
import { useEffect, useState } from "react";
import { useForm } from "react-hook-form";
import { Link, useNavigate, useParams } from "react-router-dom";
import { caseSchema, type CaseInput } from "@carebridge/shared";
import { api } from "../services/api";
import type { FundraisingCase } from "../types/api";

export function CaseEditor() {
  const { caseId } = useParams(); const navigate = useNavigate(); const editing = Boolean(caseId); const [item, setItem] = useState<FundraisingCase | null>(null); const [error, setError] = useState(""); const [summary, setSummary] = useState("");
  const form = useForm<CaseInput>({ resolver: zodResolver(caseSchema) });
  useEffect(() => { if (caseId) api.get(`/cases/${caseId}`).then(({ data }) => { setItem(data.case); form.reset({ ...data.case, targetAmount: Number(data.case.targetAmount) }); setSummary(data.case.aiSummary ?? ""); }).catch(() => setError("Could not load this case.")); }, [caseId, form]);
  async function save(values: CaseInput) { try { setError(""); const { data } = editing ? await api.patch(`/cases/${caseId}`, values) : await api.post("/cases", values); setItem(data.case); navigate(`/patient/cases/${data.case.id}`, { replace: true }); } catch (err: any) { setError(err.response?.data?.error?.message ?? "Could not save this case."); } }
  async function upload(files: FileList | null) { if (!item || !files?.length) return; try { const body = new FormData(); Array.from(files).forEach((file) => body.append("documents", file)); const { data } = await api.post(`/cases/${item.id}/documents`, body, { headers: { "Content-Type": "multipart/form-data" } }); setItem({ ...item, documents: [...item.documents, ...data.documents] }); } catch (err: any) { setError(err.response?.data?.error?.message ?? "Upload failed."); } }
  async function createSummary() { if (!item) return; try { const { data } = await api.post(`/cases/${item.id}/ai-summary`); setSummary(data.summary); } catch (err: any) { setError(err.response?.data?.error?.message ?? "Unable to generate a summary."); } }
  async function acceptSummary() { if (!item || !summary) return; try { const { data } = await api.patch(`/cases/${item.id}/ai-summary`, { summary }); setItem(data.case); } catch (err: any) { setError(err.response?.data?.error?.message ?? "Unable to save the summary."); } }
  async function submitCase() { if (!item) return; try { await api.post(`/cases/${item.id}/submit`); navigate("/patient"); } catch (err: any) { setError(err.response?.data?.error?.message ?? "Unable to submit the case."); } }
  return <main className="min-h-screen bg-slate-50 p-6 text-slate-900"><section className="mx-auto max-w-3xl"><Link to="/patient" className="text-sm font-semibold text-teal-700">← Back to dashboard</Link><h1 className="mt-5 text-3xl font-bold">{editing ? "Edit fundraising case" : "Create fundraising case"}</h1><p className="mt-2 text-slate-600">Save your case first, then upload medical documents and request an AI-written donor summary.</p><form onSubmit={form.handleSubmit(save)} className="mt-7 space-y-5 rounded-xl bg-white p-6 shadow-sm"><TextArea form={form} name="title" label="Case title" /><TextArea form={form} name="diagnosis" label="Diagnosis" /><TextArea form={form} name="treatmentPlan" label="Treatment plan" multiline /><TextArea form={form} name="story" label="Your story" multiline /><TextArea form={form} name="targetAmount" label="Funding goal (USD)" type="number" />{error && <p className="text-sm text-rose-700">{error}</p>}<button className="rounded-lg bg-teal-700 px-4 py-3 font-semibold text-white" disabled={form.formState.isSubmitting}>{form.formState.isSubmitting ? "Saving…" : "Save case"}</button></form>{item && <section className="mt-6 space-y-5 rounded-xl bg-white p-6 shadow-sm"><div><h2 className="font-bold">Medical documents</h2><input className="mt-3 block text-sm" type="file" accept="application/pdf,image/png,image/jpeg" multiple onChange={(event) => upload(event.target.files)} /><p className="mt-2 text-sm text-slate-500">PDF, PNG, or JPEG — maximum 10 MB each.</p><ul className="mt-3 list-disc pl-5 text-sm">{item.documents.map((doc) => <li key={doc.id}>{doc.fileName}</li>)}</ul></div><div><h2 className="font-bold">AI donor summary</h2><p className="mt-1 text-sm text-slate-600">Review and edit every AI suggestion before saving it.</p><button className="mt-3 rounded-lg border border-teal-700 px-3 py-2 text-sm font-semibold text-teal-700" onClick={createSummary}>Generate summary</button>{summary && <><textarea className="mt-3 min-h-28 w-full rounded-lg border p-3" value={summary} onChange={(event) => setSummary(event.target.value)} /><button className="mt-2 rounded-lg bg-teal-700 px-3 py-2 text-sm font-semibold text-white" onClick={acceptSummary}>Save accepted summary</button></>}</div><button className="rounded-lg bg-slate-900 px-4 py-3 font-semibold text-white" onClick={submitCase}>Submit for verification</button></section>}</section></main>;
}
function TextArea({ form, name, label, multiline, type = "text" }: { form: any; name: keyof CaseInput; label: string; multiline?: boolean; type?: string }) { const error = form.formState.errors[name]?.message; return <label className="block text-sm font-medium">{label}{multiline ? <textarea className="mt-1 min-h-28 w-full rounded-lg border border-slate-300 p-3" {...form.register(name)} /> : <input className="mt-1 w-full rounded-lg border border-slate-300 p-3" type={type} {...form.register(name)} />}{error && <span className="mt-1 block text-xs text-rose-700">{error}</span>}</label>; }
